apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-local-pv2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: kafka-local-storage
  hostPath:
    path: "/Volumes/SachetSSD/kube/kafka-2"