apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-local-pvol
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: zookeeper-local-storage-sc
  hostPath:
    path: "/Volumes/SachetSSD/kube/kafka"