apiVersion: v1
kind: PersistentVolume
metadata:
  name: schema-local-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: schema-local-storage
  hostPath:
    path: "/Volumes/SachetSSD/kube/kafka/schemareg"