apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-local-pv1
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mysql-local-storage
  hostPath:
    path: "/Volumes/SachetSSD/kube/mysql"