apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-local-storage
  hostPath:
    path: "/Volumes/SachetSSD/kube/redis"